version: '3.7'
services:
  sonic:
    image: valeriansaliou/sonic:v1.2.3
    ports:
      - 1491:1491
    volumes:
      - ./sonic/config.cfg:/etc/sonic.cfg
      # - sonic-data:/usr/src/sonic
      - ./sonic/store/:/var/lib/sonic/store/
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - ./data/redis:/var/lib/redis
    restart: always
  # pg_master_1:
  #   build: ./postgres/master
  #   ports:
  #     - '5445:5432'
  #   volumes:
  #     - mdata:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=postgres
  #     - PG_REP_USER=rep
  #     - PG_REP_PASSWORD=123456
  #   networks:
  #     - bridge-docker
  #   restart: always
  # pg_slave_1:
  #   build: ./postgres/slave
  #   ports:
  #     - '5446:5432'
  #   volumes:
  #     - sdata:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=postgres
  #     - PG_REP_USER=rep
  #     - PG_REP_PASSWORD=123456
  #   networks:
  #     - bridge-docker
  #   restart: always
  # pg_slave_2:
  #   build: ./postgres/slave
  #   ports:
  #     - '5447:5432'
  #   volumes:
  #     - sdata2:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=postgres
  #     - PG_REP_USER=rep
  #     - PG_REP_PASSWORD=123456
  #   networks:
  #     - bridge-docker
  #   restart: always
# volumes:
#   sonic-data:
#     driver: local
# volumes:
#   mdata:
#   sdata:
#   sdata2:
# networks:
#   bridge-docker:
#     external:
#       name: bridge-docker
